[phases.install]
cmds = [
  "npm install --include=dev",
  "npm install --prefix backend --include=dev",
  "npm install --prefix frontend --include=dev"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "npm run build --prefix backend"
]

[start]
cmd = "node backend/dist/index.js"
